CREATE DATABASE IF NOT EXISTS pagd;
USE pagd;

CREATE TABLE Guns(
    name VARCHAR(255) PRIMARY KEY,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE Reports(
    report_id INT PRIMARY KEY AUTO_INCREMENT,
    timestamp DATETIME(3) DEFAULT NOW(3) NOT NULL,
    coord VARCHAR(255) NOT NULL,
    gun VARCHAR(255) NOT NULL,
    FOREIGN KEY (gun) REFERENCES Guns(name)
);

CREATE TABLE Gunshots(
    timestamp DATETIME(3) NOT NULL,
    coord VARCHAR(255) NOT NULL,
    gun VARCHAR(255) NOT NULL,
    PRIMARY KEY (timestamp, coord),
    FOREIGN KEY (gun) REFERENCES Guns(name)
);